version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://cinematch:password123@db:5432/cinematch
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - REPLIT_DOMAINS=localhost:5000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cinematch
      - POSTGRES_USER=cinematch
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: