version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://cinematch:${DB_PASSWORD}@db:5432/cinematch
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - REPLIT_DOMAINS=${DOMAIN}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cinematch
      - POSTGRES_USER=cinematch
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: