version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://cinematch:password123@db:5432/cinematch
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - REPLIT_DOMAINS=localhost:5000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cinematch
      - POSTGRES_USER=cinematch
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: