services:
  - type: web
    name: cinematch-app
    env: node
    repo: https://github.com/Prajwal9823/CineMatchApp
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: postgresql://username:password@localhost:5432/cinematch
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        value: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNWU5MGY1MGE0YzEwMjk3MmI2NzgyZmVjYmQ4Mzg5ZiIsIm5iZiI6MTczMzE2ODY2OS45OTcsInN1YiI6IjY3NGUwZTFkYWY2YjNlMDE4MmExYzJhOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.qljFeA3s4rKeYyIP8RrNjYXCJp5IPJQFgnDXLI2uWWc
      - key: SESSION_SECRET
        sync: false
